version: '3'

services:
  service1:
    build: service1
    image: karlobencic/service1:${VERSION_SERVICE1:-latest}
    ports:
      - "8080:8080"
  service2:
    build: service2
    image: karlobencic/service2:${VERSION_SERVICE2:-latest}
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - service1
    environment:
      - SERVICE1_HOST=service1
      - SERVICE1_PORT=8080