version: '3'

services:
  service1:
    build: service1
    image: karlobencic/service1
    ports:
      - "8080:8080"
  service2:
    build: service2
    image: karlobencic/service2
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - service1