version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  publish:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: docker-compose build
      - run: docker tag karlobencic/service1 karlobencic/service1
      - run: docker tag karlobencic/service1 karlobencic/service2
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/push:
          image: karlobencic/service1 
          tag: latest
      - docker/push:
          image: karlobencic/service2 
          tag: latest

workflows:
  build-test-publish-workflow:
    jobs:
      - publish:
          context:
              - build-env-vars
              - docker-hub-creds
