version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  test-job:
    docker: 
      - image: qnib/pytest
    steps:
      - checkout
      - run: 
          name: Run tests for service 1
          command: pytest service1/tests/
      - run: 
          name: Run tests for service 2
          command: pytest service2/tests/
    parallelism: 2
  
  publish:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: docker-compose build
      - run: docker tag karlobencic/service1 karlobencic/service1:$CIRCLE_BUILD_NUM
      - run: docker tag karlobencic/service1 karlobencic/service2:$CIRCLE_BUILD_NUM
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/push:
          image: karlobencic/service1 
          tag: latest,$CIRCLE_BUILD_NUM
      - docker/push:
          image: karlobencic/service2 
          tag: latest,$CIRCLE_BUILD_NUM

workflows:
  build-test-publish-workflow:
    jobs:
      - test-job
      - publish:
          context:
              - docker-hub-creds
