apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: devops-test.me
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: service1-cluster-ip-service
                port:
                  number: 8080
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: service2-cluster-ip-service
                port:
                  number: 8080